### ISSUE TITLE
Diff does not show up in certain cases

### ISSUE THREAD

**Issue by StummeJ** [aklinker1/github-better-line-counts#15]
Github has a redesign in preview mode, but when enabled you do not get any stats. The extension just does not work

**Comment by aklinker1** [comment]
Is that something I can opt into? Like it's one of the standard preview features anyone can enable?

I'll fix it if I can get access to it.

Otherwise if you have access and want to open a PR, it's likely just a query selector that needs updated so it knows where to put the numbers.

https://github.com/aklinker1/github-better-line-counts/blob/main/src/components/DiffStat.ts#L48-L52

**Comment by StummeJ** [comment]
If you opt out of `Command Palette` then it will work on the front page, but when you go to the code page it behaves like the `Command Palette` redesign being on.

I can take a look later 🙂

**Comment by StummeJ** [comment]
With it off:
![image](https://github.com/aklinker1/github-better-line-counts/assets/3059647/7194d1e5-0ab5-43b0-9d21-3205a8825855)

With it on:
![image](https://github.com/aklinker1/github-better-line-counts/assets/3059647/01e043da-3563-48dc-9058-f3a26c4c4708)

I do see it flash in for a second then disappear

**Comment by aklinker1** [comment]
I'm a little confused by your last comment, so it's the command palette preview that breaks it? I have the command palette enabled, but don't see any issues.

The screenshots you shared of the DOM look fine, the extension should be able to find that. Maybe the URL's path has changed?

**Comment by StummeJ** [comment]
Thanks for that hint. If I don't hide the white space then it works. If the white space is hidden then it breaks. 

```diff
-https://github.com/{org}/{repo}/pull/{nnnn}/files?diff=split
+https://github.com/{org}/{repo}/pull/{nnnn}/files?diff=split&w=1
```

**Comment by aklinker1** [comment]
OK, I see what's happening. When you toggle "Hide whitespace" in github, it doesn't reload the page. So if the stats were loading or finished loading, then you toggle the whitespace, it never loads. I think adding a dom listener to reload the stats would be an easy fix.

**Comment by aklinker1** [comment]
I can work on this this weekend.

**Comment by StummeJ** [comment]
Thanks, and thanks for taking the time to make this extension!

**Comment by aklinker1** [comment]
I submitted [`v1.5.2`](https://github.com/aklinker1/github-better-line-counts/releases/tag/v1.5.2) for review. Should be out in a few days. I also created #17 to address the inaccuracies when whitespace is ignored, but I don't have a solution for that.
