### ISSUE TITLE
Doesn't work on commit and compare pages

### ISSUE THREAD

**Issue by jerrygreen** [aklinker1/github-better-line-counts#19]
For you to reproduce, check out those urls in this repository:

- `commit` page: https://github.com/aklinker1/github-better-line-counts/commit/dc0b3f01e028aaa7e0496820e7ed58a637066e0e
- `compare` page: https://github.com/aklinker1/github-better-line-counts/compare/32bbab13572a49ee846c21fd08c68166ef7f45ce...dc0b3f01e028aaa7e0496820e7ed58a637066e0e

Those both pages don't work and showing thousands lines of change.

Here I tried with my project, too:

![image](https://github.com/aklinker1/github-better-line-counts/assets/13215662/7d537f1d-ae99-4e43-97f0-5493f9d4d9f9)

**Comment by aklinker1** [comment]
From the start of the readme:

> A chrome extension that removes generated files from a **_PR's_** line count.

It's working just fine, but it only supports with PRs right now. For example: #18

<details>
<summary>Screenshot</summary>

<img width="875" alt="Screenshot 2023-07-15 at 12 48 07 PM" src="https://github.com/aklinker1/github-better-line-counts/assets/10101283/9ae5ea77-0412-4beb-a0d3-c6c60b8e1341">

</details>

Supporting commit and comparison pages would be a good idea though, so if you want to add support for them, feel free to open a PR! Otherwise I might work on this sometime.

`src/entrypoints/simple-diff.content.ts` would be a good starting point, it's where the extension checks if the url is a PR and adds the generated count to the page.

**Comment by aklinker1** [comment]
Actually, I'm gonna work on this right now. It's a good chance for me to get a feel for the DX of my new framework.

**Comment by jerrygreen** [comment]
Yeah, thank you, because I'm not able to run the project with `yarn install`:

![image](https://github.com/aklinker1/github-better-line-counts/assets/13215662/c654cae5-5d70-4d42-8e4c-1e71f96ebf24)

Nor does it work with `npm install`.

I wanted to try out pnpm but their website is blocked by Cloudflare to me.

That's a good little extension you're making.

**Comment by aklinker1** [comment]
@jerrygreen thanks! I'll try and get it working on windows (I use mac/linux as my daily driver). That's probably the problem, not `npm` vs `pnpm`.

But if you want in install `pnpm`, you can do so with `corepack enable` (for node 16 or later) or just `npm i -g pnpm`. I don't think the either option would get blocked by cloudflare... maybe?

**Comment by aklinker1** [comment]
Actually, I am wrong. That error due to NPM not using the `pnpm-lock.yaml`, and you installing a newer version of the `@webext-core/proxy-service` package, which started requiring `@webext-core/messaging` be installed as a peer dependency.

You will probably run into issues with WXT on windows as well though. I haven't tested it there yet.

**Comment by aklinker1** [comment]
Alright, work is done. @jerrygreen What do you think of this ui? I'm happy with it, and if you are to, I'll merge and submit a new version to the store.

<img width="1156" alt="Screenshot 2023-07-15 at 5 11 17 PM" src="https://github.com/aklinker1/github-better-line-counts/assets/10101283/2a88717f-de6d-44ea-9b7d-46790eb5eacb">

---

<img width="1184" alt="Screenshot 2023-07-15 at 5 11 24 PM" src="https://github.com/aklinker1/github-better-line-counts/assets/10101283/c32a9976-2636-4d96-9973-466376801367">

**Comment by jerrygreen** [comment]
Looks awesome!

And about this:

> `npm i -g pnpm`. I don't think the either option would get blocked by cloudflare... maybe?

Yeah, it’s not completely blocking me it’s just I wanted to read some docs, differences between them, maybe performance metrics or whatever they propose on their website. And the fact that they’re blocking me makes me unwilling to use their software.

Feel free to close this issue as soon as this gets delivered, good work :)

**Comment by aklinker1** [comment]
Alright, I've submitted it to the stores for review. Will be out within a few days.

https://github.com/aklinker1/github-better-line-counts/releases/tag/v1.6.0

**Comment by jerrygreen** [comment]
It... Kinda works but actually not?

I mean the extension updated, and is now showing «0 generated lines» but it doesn't count in the lock files.

Here's what I see from examples I provided above (both commit and compare pages):

![image](https://github.com/aklinker1/github-better-line-counts/assets/13215662/f7d22855-a0aa-4249-bc27-758b5d73908d)

P.S. Additionally, I don't think «0 generated lines» should be shown if there are none generated lines. Only if there are some.

**Comment by aklinker1** [comment]
Do you have the lockfile marked as generated in the repo's gitignore?

Ex: https://github.com/aklinker1/github-better-line-counts/blob/main/.gitattributes

But maybe the list of generated file patterns in the extension settings isn't working though...

I'll look at this after work

**Comment by aklinker1** [comment]
Alright, I've fixed it. I'll do another release soon. https://github.com/aklinker1/github-better-line-counts/commit/9fc04231ccd7cb2a39ca5675f13bf8822e198661

<img width="813" alt="Screenshot 2023-07-17 at 5 38 13 PM" src="https://github.com/aklinker1/github-better-line-counts/assets/10101283/96939a1e-29b9-4467-a76f-9ff5b90b4349">

**Comment by aklinker1** [comment]
Submitted it for review just now. check back in 1 day.

**Comment by jerrygreen** [comment]
It works now! 🎉
