### ISSUE TITLE
Couldn't count generated lines for private repo

### ISSUE THREAD

**Issue by jerrygreen** [aklinker1/github-better-line-counts#23]
I know there's mention of this:

> Optional: To load the `.gitattributes` for private repos, you need to enter a GitHub personal access token.

But the thing is... I don't need nor use `.gitattributes`. For me the basic functionality is just enough.

Currently it just hangs into this state infinitely:

> ![gif2](https://github.com/aklinker1/github-better-line-counts/assets/13215662/dda2227d-2f56-468c-ad65-e5a4f0c33862)

IMO for simple cases without `.gitattributes`, – extension has all the info just on the page: token shouldn't be needed.

I just tried to add github token though, and it suddenly worked. But it shouldn't require it.

I think it is a minor issue yet important enough to mention.

**Comment by aklinker1** [comment]
The label could be better:

> Optional: To recalculate the diff on private repos, the extension needs a GitHub PAT to authenticate API requests.

Loading the gitattributes file is only one of the API calls made using the token. The others involve loading information about the current PR or commits, and PAGINATING through all files for very large diffs.

> IMO for simple cases without .gitattributes, – extension has all the info just on the page: token shouldn't be needed.

When I started working on this extension originally, I attempted to find the required information from the page, but when lots of files change, GitHub does not load everything all at once, so some of the line counts I need are missing.

Using the API solves this problem and one other big one: ongoing maintenance. I don't want to fix the extension every time GitHub changes their UI and potentially breaks the query selectors used to find the line counts.

**Comment by aklinker1** [comment]
I'll fix the issue with the spinner not going away and update the token's label, but I'm not going to attempt to parse the page to recalculate the diff.

_Edit: done. [`v1.6.2`](https://github.com/aklinker1/github-better-line-counts/releases/tag/v1.6.2)_

**Comment by aklinker1** [comment]
For future reference, here is the code that uses the PAT to load the current commit, check for a `.gitattributes` file, and recalculate the diff.

https://github.com/aklinker1/github-better-line-counts/blob/aff927f3c3536c6a27af47b1c6be2362005ef5ed/src/utils/github/service.ts#L113
