### ISSUE TITLE
Counts wrongly calculated for multiple commits at `compare` page

### ISSUE THREAD

**Issue by jerrygreen** [aklinker1/github-better-line-counts#24]
The reason why the bug appears, it seems:

- It does not calculate the sum of the commit changes. Only the changes for the last commit.

Here an example for reproducing: https://github.com/aklinker1/github-better-line-counts/compare/4f6cf9cd6b4b69447b563ad945d2f6c65325ff15...aff927f3c3536c6a27af47b1c6be2362005ef5ed

It shows: 1 additions, 1 deletions, 0 generated
Should be: 38 additions, 27 deletions, 0 generated

Preview:

> 
![image](https://github.com/aklinker1/github-better-line-counts/assets/13215662/fe94c02d-02d4-40b1-828b-43ecb5d340d6)

**Comment by jerrygreen** [comment]
All of a sudden the previous example works correctly now.

But I found another example with similar problem: https://github.com/aklinker1/github-better-line-counts/compare/8a4ba0e402f3f623ccd21b8cc02a2078b8899465...b91101fca235756183879e3754e38a9be39ac7fc

Shows: `+19, -2`
Should: `+144, -11`

![image](https://github.com/aklinker1/github-better-line-counts/assets/13215662/c0d1b8e7-a0cd-4614-b728-ccd06c929391)

**Comment by jerrygreen** [comment]
Not sure why this appears exactly. It seems my initial assumption is wrong:

> It does not calculate the sum of the commit changes. **_Only the changes for the last commit_**

Commits have nothing to do with this, it seems.

It now seems to me it's related to some outdated cache or something.

**Comment by aklinker1** [comment]
Yup, it's a caching issue. I need to use a different cache key for multiple commits, I just use the starting commit. 

https://github.com/aklinker1/github-better-line-counts/blob/aff927f3c3536c6a27af47b1c6be2362005ef5ed/src/utils/github/service.ts#L116-L121

**Comment by aklinker1** [comment]
Fixed in [`v1.6.3`](https://github.com/aklinker1/github-better-line-counts/releases/tag/v1.6.3)

**Comment by jerrygreen** [comment]
It... Kind of returned? Might not be the same exact thing, but it shows zeros by some reason to me now:

![gif](https://github.com/aklinker1/github-better-line-counts/assets/13215662/3cb16d7a-0899-4511-90d0-0e9c3eae23bb)

I'm still using `1.6.3`.

In this exact case I don't have any generated code at all. But that doesn't seem to be the only reason.

Not sure why it's happening exactly.

**Comment by aklinker1** [comment]
Is this a URL I can visit? Otherwise I won't be able to investigate.

The extension logs how it calculates the stats, could you open the dev console, and show debug messages?
