### ISSUE TITLE
Hover over changes to view original diff

### ISSUE THREAD

**Issue by aaronklinker-st** [aklinker1/github-better-line-counts#28]
Sometimes, when upgrading dependencies, it's nice to know the original count to see how many dependencies were added/removed. 

So when hovering over the generated number, it should show the generated + and - for a quick reference.

**Comment by aklinker1** [comment]
Closed by https://github.com/aklinker1/github-better-line-counts/commit/dfac46f5958716fa3789a7f95827cf3d9ec798b8
