### ISSUE TITLE
Failed to calculate diff: FetchError -- returns 404

### ISSUE THREAD

**Issue by seanhagen** [aklinker1/github-better-line-counts#30]
This is for a private organization repository that uses SSO, so I'm not sure if this is an expected behaviour or not. I made sure to authorize the personal access token for the organization, but still no luck.

When I run this on the command line ( with the token, owner, repo, & pull number filled in properly ) it does return a JSON response though:

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/pulls/PULL_NUMBER
```

**Comment by aklinker1** [comment]
The extension makes a network request in the background, could you inspect it and compare the request that's returning a 404 with the one from the CLI that works?

1. Enter `chrome://extensions` in your navigation bar
2. Ensure "Developer Mode" is turned on, there's a switch in the top right corner
3. Find "GitHub: Better Line Counts" and inspect the service worker
4. Switch to the network tab in the devtools window that popped up
5. Reload the page (there's a 1hr cache, so maybe visit a PR on the same repo you haven't looked at recently?)

The URL should look more like this:

```
https://api.github.com/repos/wxt-dev/wxt/pulls/344/files?page=1&per_page=100
```

Here's a video walking you through the process of inspecting network requests:

https://github.com/aklinker1/github-better-line-counts/assets/10101283/b16903e3-2074-4242-828c-c3be0f69656f

**Comment by aklinker1** [comment]
~~Actually, are you using `github.com`, or are you using `github.<company-name>.com`? All API calls are made to `github.com`, so that would explain your 404.~~

Edit: No, of course you're not. Your example request is to `api.github.com`, and the extension doesn't even run on `github.<company-name>.com`... Please see the above comment and help with the debugging.

**Comment by seanhagen** [comment]
I don't know what changed, but it's all working now:

![image](https://github.com/aklinker1/github-better-line-counts/assets/444767/25be1f7b-5625-4c94-ab97-16473fb25d97)

( from a PR I'm working on right now )
